# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Shady Fragments
tagline:          'A Graphics Programmer''s Blog'
description:      'Dumping ground for thoughts of a graphics programmer, <a href="http://twitter.com/vec3f" target="_blank">@vec3f</a>.'
url:              http://vec3f.github.io
baseurl:          /

paginate:         5

# Custom vars
author:
  email:          # your email address
  github:         vec3f
  linkedin:       namakshenas
  twitter:        vec3f
  stackoverflow:  # your stackoverflow profile, e.g. "users/50476/bart-kiers"
